### ISSUE TITLE
Replace moldy and low res icons with high resolution ones

### ISSUE THREAD

**Issue by frblo** [datasektionen/aaallt2#9]
Many of the icons used on aaallt are really low resolution, and have started rotting. They should all be replaced with beutiful svgs.

![image](https://github.com/user-attachments/assets/770a9e67-27ce-4d9d-897c-4b65ed605a82)

**Comment by Herkarl** [comment]
Do note that most (all?) of the icons used are the favicons provided by the systems themself, so the best approach would be to update those at the source. Some of them probably provide svg favicons already (i.e. github), and we would only have to change to use those instead.

**Comment by frblo** [comment]
While that is true, it's an excuse for @foodelevator being lazy.

**Comment by foodelevator** [comment]
Sorry, I've been too busy bringing in money to the chapter buy playing pirots on htttps://sm.datasektionen.se/
